"""
Trinity Backend - Middleware Package
Rate limiting, ICP caching, observability, A/B testing, and request utilities
"""

from .ab_test import (
    experiment,
    experiments,
    get_all_experiment_assignments,
    get_experiment_config,
    get_session_id,
    get_variant_name,
    is_in_variant,
    record_exposure,
)
from .icp_cache import icp_cache, icp_idempotent
from .observability import (  # Phase 4: Experiment metrics; Phase 5: Cost optimization metrics
    AUTH_ATTEMPTS,
    EMBEDDING_CACHE_HITS,
    EMBEDDING_CACHE_MISSES,
    EMBEDDING_CACHE_SIZE,
    ERROR_COUNTER,
    ESTIMATED_COST_USD,
    EXPERIMENT_ASSIGNMENTS,
    EXPERIMENT_EXPOSURES,
    INFERENCE_DURATION,
    PARALLEL_EXECUTIONS,
    PARALLEL_LATENCY,
    PROMETHEUS_AVAILABLE,
    REQUEST_COUNTER,
    REQUEST_LATENCY,
    SEMANTIC_CACHE_HITS,
    SEMANTIC_CACHE_MISSES,
    SEMANTIC_CACHE_SIMILARITY,
    SEMANTIC_CACHE_SIZE,
    TOKEN_RATE,
    TOKENS_COMPLETION,
    TOKENS_GENERATED,
    TOKENS_PROMPT,
    USER_TOKENS,
    get_metrics_response,
    observe_endpoint,
    set_model_loaded,
    set_uptime,
    track_auth,
    track_error,
    track_inference,
    track_request,
    track_storage,
    update_system_metrics,
)
from .rate_limit import (
    RATE_LIMIT,
    RATE_WINDOW,
    STORAGE_RATE_LIMIT,
    STORAGE_RATE_WINDOW,
    rate_limit,
    request_counts,
    storage_rate_limit,
    storage_request_counts,
)

__all__ = [
    "rate_limit",
    "storage_rate_limit",
    "request_counts",
    "RATE_LIMIT",
    "RATE_WINDOW",
    "storage_request_counts",
    "STORAGE_RATE_LIMIT",
    "STORAGE_RATE_WINDOW",
    "icp_idempotent",
    "icp_cache",
    # Observability exports
    "PROMETHEUS_AVAILABLE",
    "track_request",
    "track_inference",
    "track_storage",
    "track_auth",
    "observe_endpoint",
    "track_error",
    "get_metrics_response",
    "update_system_metrics",
    "set_model_loaded",
    "set_uptime",
    "REQUEST_COUNTER",
    "REQUEST_LATENCY",
    "ERROR_COUNTER",
    "INFERENCE_DURATION",
    "TOKENS_GENERATED",
    "AUTH_ATTEMPTS",
    # Phase 4: Experiment exports
    "EXPERIMENT_ASSIGNMENTS",
    "EXPERIMENT_EXPOSURES",
    "PARALLEL_EXECUTIONS",
    "PARALLEL_LATENCY",
    "experiment",
    "experiments",
    "get_session_id",
    "get_experiment_config",
    "get_variant_name",
    "is_in_variant",
    "record_exposure",
    "get_all_experiment_assignments",
    # Phase 5: Cost optimization exports
    "EMBEDDING_CACHE_HITS",
    "EMBEDDING_CACHE_MISSES",
    "EMBEDDING_CACHE_SIZE",
    "SEMANTIC_CACHE_HITS",
    "SEMANTIC_CACHE_MISSES",
    "SEMANTIC_CACHE_SIZE",
    "SEMANTIC_CACHE_SIMILARITY",
    "TOKENS_PROMPT",
    "TOKENS_COMPLETION",
    "ESTIMATED_COST_USD",
    "TOKEN_RATE",
    "USER_TOKENS",
]
