"""
Trinity Backend - Middleware Package
Rate limiting, ICP caching, observability, and request utilities
"""

from .icp_cache import icp_cache, icp_idempotent
from .observability import (  # Phase 5: Cost optimization metrics
    AUTH_ATTEMPTS,
    EMBEDDING_CACHE_HITS,
    EMBEDDING_CACHE_MISSES,
    EMBEDDING_CACHE_SIZE,
    ERROR_COUNTER,
    ESTIMATED_COST_USD,
    INFERENCE_DURATION,
    PROMETHEUS_AVAILABLE,
    REQUEST_COUNTER,
    REQUEST_LATENCY,
    SEMANTIC_CACHE_HITS,
    SEMANTIC_CACHE_MISSES,
    SEMANTIC_CACHE_SIMILARITY,
    SEMANTIC_CACHE_SIZE,
    TOKEN_RATE,
    TOKENS_COMPLETION,
    TOKENS_GENERATED,
    TOKENS_PROMPT,
    USER_TOKENS,
    # Legacy metrics compatibility (Phase 5.5A migration)
    end_request,
    get_active_requests,
    get_metrics_response,
    get_prometheus_summary,
    get_system_info,
    observe_endpoint,
    record_request,
    set_model_loaded,
    set_uptime,
    start_request,
    track_auth,
    track_error,
    track_inference,
    track_request,
    track_storage,
    update_system_metrics,
)
from .rate_limit import (
    RATE_LIMIT,
    RATE_WINDOW,
    STORAGE_RATE_LIMIT,
    STORAGE_RATE_WINDOW,
    add_rate_limit_headers,
    get_rate_limit_info,
    rate_limit,
    request_counts,
    storage_rate_limit,
    storage_request_counts,
)

__all__ = [
    "rate_limit",
    "storage_rate_limit",
    "request_counts",
    "RATE_LIMIT",
    "RATE_WINDOW",
    "storage_request_counts",
    "STORAGE_RATE_LIMIT",
    "STORAGE_RATE_WINDOW",
    "add_rate_limit_headers",
    "get_rate_limit_info",
    "icp_idempotent",
    "icp_cache",
    # Observability exports
    "PROMETHEUS_AVAILABLE",
    "track_request",
    "track_inference",
    "track_storage",
    "track_auth",
    "observe_endpoint",
    "track_error",
    "get_metrics_response",
    "update_system_metrics",
    "set_model_loaded",
    "set_uptime",
    "REQUEST_COUNTER",
    "REQUEST_LATENCY",
    "ERROR_COUNTER",
    "INFERENCE_DURATION",
    "TOKENS_GENERATED",
    "AUTH_ATTEMPTS",
    # Phase 5: Cost optimization exports
    "EMBEDDING_CACHE_HITS",
    "EMBEDDING_CACHE_MISSES",
    "EMBEDDING_CACHE_SIZE",
    "SEMANTIC_CACHE_HITS",
    "SEMANTIC_CACHE_MISSES",
    "SEMANTIC_CACHE_SIZE",
    "SEMANTIC_CACHE_SIMILARITY",
    "TOKENS_PROMPT",
    "TOKENS_COMPLETION",
    "ESTIMATED_COST_USD",
    "TOKEN_RATE",
    "USER_TOKENS",
    # Phase 5.5A: Legacy metrics migration
    "start_request",
    "end_request",
    "record_request",
    "get_active_requests",
    "get_prometheus_summary",
    "get_system_info",
]
