"""
Trinity Backend - Observability Middleware
Production-grade Prometheus metrics for monitoring, alerting, and SLO tracking.

Metrics follow the RED method (Rate, Errors, Duration) plus USE method for resources.
Labels enable multi-dimensional analysis in Grafana.

Usage:
    from middleware.observability import (
        track_request, track_inference, track_error,
        REQUEST_LATENCY, INFERENCE_DURATION, ERROR_COUNTER
    )

    # In request handler:
    with track_request(endpoint='/generate', method='POST'):
        response = process_request()

    # For inference timing:
    with track_inference(model='llama3.1:8b', tier='2'):
        result = run_inference()
"""

import functools
import logging
import threading
import time
from contextlib import contextmanager
from typing import Callable, Dict

logger = logging.getLogger(__name__)


# No-op fallback class (always defined for testability)
class NoOpMetric:
    """Fallback metric that does nothing when Prometheus is unavailable"""

    def labels(self, **kwargs):
        return self

    def inc(self, amount=1):
        pass

    def dec(self, amount=1):
        pass

    def set(self, value):
        pass

    def observe(self, value):
        pass

    def time(self):
        return contextmanager(lambda: (yield))()


# Prometheus client availability check
PROMETHEUS_AVAILABLE = False
try:
    from prometheus_client import (
        CONTENT_TYPE_LATEST,
        REGISTRY,
        Counter,
        Gauge,
        Histogram,
        Summary,
        generate_latest,
    )

    PROMETHEUS_AVAILABLE = True
    logger.info("Prometheus client loaded successfully")
except ImportError:
    logger.warning("prometheus-client not installed - metrics disabled")
    # Use NoOpMetric as fallback
    Counter = Histogram = Gauge = Summary = lambda *a, **kw: NoOpMetric()
    REGISTRY = None
    generate_latest = lambda r=None: b""
    CONTENT_TYPE_LATEST = "text/plain"


# =============================================================================
# METRIC DEFINITIONS
# =============================================================================

# Request metrics (RED method)
REQUEST_COUNTER = (
    Counter(
        "trinity_http_requests_total",
        "Total HTTP requests by endpoint, method, and status",
        ["endpoint", "method", "status"],
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

REQUEST_LATENCY = (
    Histogram(
        "trinity_http_request_duration_seconds",
        "HTTP request latency in seconds",
        ["endpoint", "method"],
        buckets=(0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

REQUEST_IN_PROGRESS = (
    Gauge(
        "trinity_http_requests_in_progress",
        "Number of HTTP requests currently being processed",
        ["endpoint"],
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

# Inference metrics
INFERENCE_COUNTER = (
    Counter(
        "trinity_inference_total",
        "Total inference requests by model and tier",
        ["model", "tier", "status"],
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

INFERENCE_DURATION = (
    Histogram(
        "trinity_inference_duration_seconds",
        "Model inference latency in seconds",
        ["model", "tier"],
        buckets=(0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0, 120.0, 300.0),
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

TOKENS_GENERATED = (
    Counter("trinity_tokens_generated_total", "Total tokens generated by model", ["model", "tier"])
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

TOKENS_PER_SECOND = (
    Summary("trinity_tokens_per_second", "Token generation rate", ["model", "tier"])
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

# Error metrics
ERROR_COUNTER = (
    Counter("trinity_errors_total", "Total errors by type and endpoint", ["error_type", "endpoint"])
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

# Storage metrics
STORAGE_OPERATIONS = (
    Counter(
        "trinity_storage_operations_total",
        "Storage operations by type and status",
        ["operation", "status"],
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

STORAGE_LATENCY = (
    Histogram(
        "trinity_storage_latency_seconds",
        "Storage operation latency",
        ["operation"],
        buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0),
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

# Authentication metrics
AUTH_ATTEMPTS = (
    Counter(
        "trinity_auth_attempts_total",
        "Authentication attempts by status",
        ["status", "failure_reason"],
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

AUTH_LATENCY = (
    Histogram(
        "trinity_auth_latency_seconds",
        "Authentication verification latency",
        buckets=(0.001, 0.005, 0.01, 0.025, 0.05, 0.1),
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

# System resource metrics (USE method)
SYSTEM_CPU = (
    Gauge("trinity_system_cpu_percent", "System CPU utilization percentage")
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

SYSTEM_MEMORY = (
    Gauge("trinity_system_memory_percent", "System memory utilization percentage")
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

SYSTEM_MEMORY_AVAILABLE_MB = (
    Gauge("trinity_system_memory_available_mb", "Available system memory in MB")
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

# Application health
UPTIME_SECONDS = (
    Gauge("trinity_uptime_seconds", "Application uptime in seconds")
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

ACTIVE_CONNECTIONS = (
    Gauge("trinity_active_connections", "Number of active client connections")
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

MODEL_LOADED = (
    Gauge("trinity_model_loaded", "Whether the LLM model is loaded and ready", ["model", "tier"])
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)


# =============================================================================
# AGENT PIPELINE METRICS (Phase 2B)
# =============================================================================

# Agent pass duration tracking
AGENT_PASS_DURATION = (
    Histogram(
        "trinity_agent_pass_duration_seconds",
        "Duration of each agent pipeline pass",
        ["pass_type"],
        buckets=(0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0, 120.0, 300.0),
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

AGENT_PASS_COUNTER = (
    Counter(
        "trinity_agent_passes_total",
        "Total agent passes by type and status",
        ["pass_type", "status"],
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

# Complexity classification metrics
COMPLEXITY_CLASSIFICATIONS = (
    Counter(
        "trinity_complexity_classifications_total", "Question complexity distribution", ["level"]
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

COMPLEXITY_ROUTING = (
    Counter(
        "trinity_complexity_routing_total",
        "Routing decisions based on complexity",
        ["route"],  # 'agent'
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

# Tool execution metrics
TOOL_CALLS = (
    Counter(
        "trinity_tool_calls_total", "Tool invocations by tool name and status", ["tool", "status"]
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

TOOL_DURATION = (
    Histogram(
        "trinity_tool_duration_seconds",
        "Tool execution duration",
        ["tool"],
        buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0),
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)



# =============================================================================
# COST OPTIMIZATION METRICS (Phase 5)
# =============================================================================

# Embedding cache metrics
EMBEDDING_CACHE_HITS = (
    Counter("trinity_embedding_cache_hits_total", "Embedding cache hits")
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

EMBEDDING_CACHE_MISSES = (
    Counter("trinity_embedding_cache_misses_total", "Embedding cache misses")
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

EMBEDDING_CACHE_SIZE = (
    Gauge("trinity_embedding_cache_size", "Current number of embeddings in cache")
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

# Semantic response cache metrics
SEMANTIC_CACHE_HITS = (
    Counter("trinity_semantic_cache_hits_total", "Semantic response cache hits")
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

SEMANTIC_CACHE_MISSES = (
    Counter("trinity_semantic_cache_misses_total", "Semantic response cache misses")
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

SEMANTIC_CACHE_SIZE = (
    Gauge("trinity_semantic_cache_size", "Current number of responses in semantic cache")
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

SEMANTIC_CACHE_SIMILARITY = (
    Histogram(
        "trinity_semantic_cache_similarity",
        "Similarity scores for semantic cache hits",
        buckets=(0.90, 0.92, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.0),
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

# Token usage metrics
TOKENS_PROMPT = (
    Counter("trinity_tokens_prompt_total", "Total prompt tokens processed", ["model"])
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

TOKENS_COMPLETION = (
    Counter("trinity_tokens_completion_total", "Total completion tokens generated", ["model"])
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

ESTIMATED_COST_USD = (
    Counter("trinity_estimated_cost_usd_total", "Estimated total cost in USD", ["model"])
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

TOKEN_RATE = (
    Summary("trinity_token_generation_rate", "Tokens generated per second", ["model"])
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)

# Per-user usage
USER_TOKENS = (
    Counter(
        "trinity_user_tokens_total",
        "Tokens used per user",
        ["user_id", "type"],  # type: 'prompt' or 'completion'
    )
    if PROMETHEUS_AVAILABLE
    else NoOpMetric()
)


# =============================================================================
# CONTEXT MANAGERS FOR METRIC COLLECTION
# =============================================================================


@contextmanager
def track_request(endpoint: str, method: str = "GET"):
    """
    Context manager to track HTTP request metrics.

    Usage:
        with track_request('/generate', 'POST') as tracker:
            result = handle_request()
            tracker.set_status(200)  # or 500 for errors
    """
    start_time = time.perf_counter()
    REQUEST_IN_PROGRESS.labels(endpoint=endpoint).inc()

    class RequestTracker:
        def __init__(self):
            self.status = "200"

        def set_status(self, code: int):
            self.status = str(code)

    tracker = RequestTracker()

    try:
        yield tracker
    except Exception as e:
        tracker.status = "500"
        ERROR_COUNTER.labels(error_type=type(e).__name__, endpoint=endpoint).inc()
        raise
    finally:
        duration = time.perf_counter() - start_time
        REQUEST_LATENCY.labels(endpoint=endpoint, method=method).observe(duration)
        REQUEST_COUNTER.labels(endpoint=endpoint, method=method, status=tracker.status).inc()
        REQUEST_IN_PROGRESS.labels(endpoint=endpoint).dec()


@contextmanager
def track_inference(model: str, tier: str = "unknown"):
    """
    Context manager to track model inference metrics.

    Usage:
        with track_inference('llama3.1:8b', tier='2') as tracker:
            result = run_model_inference()
            tracker.set_tokens(result.token_count)
    """
    start_time = time.perf_counter()

    class InferenceTracker:
        def __init__(self):
            self.status = "success"
            self.tokens = 0

        def set_status(self, status: str):
            self.status = status

        def set_tokens(self, count: int):
            self.tokens = count

    tracker = InferenceTracker()

    try:
        yield tracker
    except Exception as e:
        tracker.status = "error"
        ERROR_COUNTER.labels(error_type=type(e).__name__, endpoint="/inference").inc()
        raise
    finally:
        duration = time.perf_counter() - start_time
        INFERENCE_DURATION.labels(model=model, tier=tier).observe(duration)
        INFERENCE_COUNTER.labels(model=model, tier=tier, status=tracker.status).inc()

        if tracker.tokens > 0:
            TOKENS_GENERATED.labels(model=model, tier=tier).inc(tracker.tokens)
            if duration > 0:
                TOKENS_PER_SECOND.labels(model=model, tier=tier).observe(tracker.tokens / duration)


@contextmanager
def track_storage(operation: str):
    """
    Context manager to track storage operation metrics.

    Usage:
        with track_storage('save_chat'):
            save_encrypted_chat(data)
    """
    start_time = time.perf_counter()
    status = "success"

    try:
        yield
    except Exception:
        status = "error"
        raise
    finally:
        duration = time.perf_counter() - start_time
        STORAGE_LATENCY.labels(operation=operation).observe(duration)
        STORAGE_OPERATIONS.labels(operation=operation, status=status).inc()


@contextmanager
def track_auth():
    """
    Context manager to track authentication metrics.

    Usage:
        with track_auth() as tracker:
            result = verify_signature(...)
            if not result:
                tracker.set_failure('invalid_signature')
    """
    start_time = time.perf_counter()

    class AuthTracker:
        def __init__(self):
            self.status = "success"
            self.failure_reason = "none"

        def set_failure(self, reason: str):
            self.status = "failure"
            self.failure_reason = reason

    tracker = AuthTracker()

    try:
        yield tracker
    except Exception as e:
        tracker.status = "error"
        tracker.failure_reason = type(e).__name__
        raise
    finally:
        duration = time.perf_counter() - start_time
        AUTH_LATENCY.observe(duration)
        AUTH_ATTEMPTS.labels(status=tracker.status, failure_reason=tracker.failure_reason).inc()


# =============================================================================
# AGENT PIPELINE CONTEXT MANAGERS (Phase 2B)
# =============================================================================


@contextmanager
def track_agent_pass(pass_type: str):
    """
    Context manager to track agent pipeline pass execution.

    Usage:
        with track_agent_pass('understand') as tracker:
            result = execute_understand_pass()
            if failed:
                tracker.set_status('error')

    Pass types: understand, plan, execute, critique, refine
    """
    start_time = time.perf_counter()

    class PassTracker:
        def __init__(self):
            self.status = "success"

        def set_status(self, status: str):
            self.status = status

    tracker = PassTracker()

    try:
        yield tracker
    except Exception:
        tracker.status = "error"
        raise
    finally:
        duration = time.perf_counter() - start_time
        AGENT_PASS_DURATION.labels(pass_type=pass_type).observe(duration)
        AGENT_PASS_COUNTER.labels(pass_type=pass_type, status=tracker.status).inc()


@contextmanager
def track_tool_call(tool_name: str):
    """
    Context manager to track tool execution.

    Usage:
        with track_tool_call('web_search') as tracker:
            result = execute_web_search(query)
            if result.error:
                tracker.set_status('error')
    """
    start_time = time.perf_counter()

    class ToolTracker:
        def __init__(self):
            self.status = "success"

        def set_status(self, status: str):
            self.status = status

    tracker = ToolTracker()

    try:
        yield tracker
    except Exception:
        tracker.status = "error"
        raise
    finally:
        duration = time.perf_counter() - start_time
        TOOL_DURATION.labels(tool=tool_name).observe(duration)
        TOOL_CALLS.labels(tool=tool_name, status=tracker.status).inc()


def record_complexity(level: str):
    """Record a complexity classification."""
    COMPLEXITY_CLASSIFICATIONS.labels(level=level).inc()


def record_routing(route: str):
    """Record a routing decision."""
    COMPLEXITY_ROUTING.labels(route=route).inc()



# =============================================================================
# DECORATOR FOR AUTOMATIC REQUEST TRACKING
# =============================================================================


def observe_endpoint(endpoint: str = None):
    """
    Decorator to automatically track request metrics for Flask endpoints.

    Usage:
        @app.route('/generate', methods=['POST'])
        @observe_endpoint('/generate')
        def generate():
            ...
    """

    def decorator(func: Callable) -> Callable:
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            # Auto-detect endpoint if not provided
            ep = endpoint or func.__name__

            with track_request(ep, method="POST") as tracker:
                try:
                    result = func(*args, **kwargs)
                    # Try to extract status code from Flask response
                    if hasattr(result, "status_code"):
                        tracker.set_status(result.status_code)
                    elif isinstance(result, tuple) and len(result) >= 2:
                        tracker.set_status(result[1])
                    return result
                except Exception:
                    tracker.set_status(500)
                    raise

        return wrapper

    return decorator


# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================


def track_error(error_type: str, endpoint: str = "unknown"):
    """Convenience function to track an error"""
    ERROR_COUNTER.labels(error_type=error_type, endpoint=endpoint).inc()


def update_system_metrics():
    """Update system resource metrics (call periodically)"""
    if not PROMETHEUS_AVAILABLE:
        return

    try:
        import psutil

        SYSTEM_CPU.set(psutil.cpu_percent(interval=None))
        memory = psutil.virtual_memory()
        SYSTEM_MEMORY.set(memory.percent)
        SYSTEM_MEMORY_AVAILABLE_MB.set(memory.available / (1024 * 1024))
    except ImportError:
        pass


def set_model_loaded(model: str, tier: str, loaded: bool = True):
    """Mark a model as loaded/unloaded"""
    MODEL_LOADED.labels(model=model, tier=tier).set(1 if loaded else 0)


def set_uptime(seconds: float):
    """Update uptime metric"""
    UPTIME_SECONDS.set(seconds)


# Global tracking for legacy metrics compatibility
_start_time = time.time()
_total_requests = 0
_successful_requests = 0
_failed_requests = 0
_total_tokens_generated = 0
_total_latency_ms = 0
_active_requests = 0
_metrics_lock = threading.Lock()


def start_request():
    """Increment active request counter (legacy compatibility)"""
    global _active_requests
    with _metrics_lock:
        _active_requests += 1


def end_request():
    """Decrement active request counter (legacy compatibility)"""
    global _active_requests
    with _metrics_lock:
        _active_requests = max(0, _active_requests - 1)


def record_request(success: bool, tokens: int = 0, latency_ms: float = 0):
    """Record metrics for a completed request (legacy compatibility)"""
    global _total_requests, _successful_requests, _failed_requests
    global _total_tokens_generated, _total_latency_ms

    with _metrics_lock:
        _total_requests += 1
        if success:
            _successful_requests += 1
            _total_tokens_generated += tokens
            _total_latency_ms += latency_ms
        else:
            _failed_requests += 1


def get_active_requests() -> int:
    """Get current active request count"""
    with _metrics_lock:
        return _active_requests


def get_prometheus_summary() -> Dict:
    """
    Generate summary metrics for /health endpoint.
    Replaces services.metrics.get_stats() with Prometheus-compatible data.

    Returns dict compatible with legacy metrics.get_stats():
        - total_requests
        - successful_requests
        - failed_requests
        - success_rate
        - total_tokens_generated
        - avg_latency_ms
        - active_requests
        - uptime_seconds
    """
    global _total_requests, _successful_requests, _failed_requests
    global _total_tokens_generated, _total_latency_ms, _active_requests, _start_time

    with _metrics_lock:
        uptime = time.time() - _start_time
        avg_latency = (
            _total_latency_ms / _successful_requests if _successful_requests > 0 else 0
        )

        return {
            "total_requests": _total_requests,
            "successful_requests": _successful_requests,
            "failed_requests": _failed_requests,
            "success_rate": (
                _successful_requests / _total_requests * 100
                if _total_requests > 0
                else 100
            ),
            "total_tokens_generated": _total_tokens_generated,
            "avg_latency_ms": avg_latency,
            "active_requests": _active_requests,
            "uptime_seconds": uptime,
        }


def get_system_info() -> Dict:
    """
    Get system resource information (CPU, memory).
    Moved from services.metrics for consolidation.
    """
    try:
        import psutil

        cpu_percent = psutil.cpu_percent(interval=0.1)
        memory = psutil.virtual_memory()

        return {
            "cpu_percent": cpu_percent,
            "memory_percent": memory.percent,
            "memory_available_mb": memory.available / (1024 * 1024),
        }
    except ImportError:
        logger.warning("psutil not installed - system metrics unavailable")
        return {
            "cpu_percent": 0,
            "memory_percent": 0,
            "memory_available_mb": 0,
        }


def get_metrics_response():
    """
    Generate Prometheus metrics response for /metrics endpoint.

    Returns:
        Tuple of (content, content_type) for Flask response
    """
    if not PROMETHEUS_AVAILABLE:
        return b"# Prometheus client not installed\n", "text/plain"

    # Update system metrics before serving
    update_system_metrics()

    return generate_latest(REGISTRY), CONTENT_TYPE_LATEST


# =============================================================================
# EXPORTS
# =============================================================================

__all__ = [
    # Availability flag
    "PROMETHEUS_AVAILABLE",
    # Request metrics
    "REQUEST_COUNTER",
    "REQUEST_LATENCY",
    "REQUEST_IN_PROGRESS",
    # Inference metrics
    "INFERENCE_COUNTER",
    "INFERENCE_DURATION",
    "TOKENS_GENERATED",
    "TOKENS_PER_SECOND",
    # Error metrics
    "ERROR_COUNTER",
    # Storage metrics
    "STORAGE_OPERATIONS",
    "STORAGE_LATENCY",
    # Auth metrics
    "AUTH_ATTEMPTS",
    "AUTH_LATENCY",
    # System metrics
    "SYSTEM_CPU",
    "SYSTEM_MEMORY",
    "SYSTEM_MEMORY_AVAILABLE_MB",
    "UPTIME_SECONDS",
    "ACTIVE_CONNECTIONS",
    "MODEL_LOADED",
    # Agent pipeline metrics (Phase 2B)
    "AGENT_PASS_DURATION",
    "AGENT_PASS_COUNTER",
    "COMPLEXITY_CLASSIFICATIONS",
    "COMPLEXITY_ROUTING",
    "TOOL_CALLS",
    "TOOL_DURATION",
    # Context managers
    "track_request",
    "track_inference",
    "track_storage",
    "track_auth",
    "track_agent_pass",
    "track_tool_call",
    # Decorator
    "observe_endpoint",
    # Utility functions
    "track_error",
    "update_system_metrics",
    "set_model_loaded",
    "set_uptime",
    "get_metrics_response",
    "record_complexity",
    "record_routing",
    # Legacy metrics compatibility (Phase 5.5A migration)
    "start_request",
    "end_request",
    "record_request",
    "get_active_requests",
    "get_prometheus_summary",
    "get_system_info",
    # Fallback class (for testing)
    "NoOpMetric",
]
